[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200

[[headers]]
  # Aturan header untuk semua rute
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers: "Content-Type",
    Access-Control-Allow-Methods: "GET, POST, PUT, DELETE",